services:
  nginx:
    build: ../nginx
    container_name: nginx
    image: ft_nginx
    ports:
      - "443:443"
    networks:
      - public_net
      - internal_net
    depends_on:
      backend_api:
        condition: service_started
    restart: always

  front_end:
    build:
      context: ../../netpong-app
      dockerfile: ../infra/frontend/Dockerfile
    container_name: front_end
    image: ft_frontend
    networks:
      - internal_net
    depends_on:
      - backend_api
    restart: always

  backend_api:
    build:
      context: ../../backend_srcs
      dockerfile: ../infra/backend/Dockerfile
    container_name: backend_api
    image: ft_backend_api
    env_file:
      - ../env/backend.env
    networks:
      - internal_net
    depends_on:
      database:
        condition: service_healthy
    restart: always


  database:
    image: postgres:17
    container_name: database
    env_file:
      - ../env/database.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  public_net:
    driver: bridge
  internal_net:
    driver: bridge
